import os as _os
import pandas as pd
import numpy as np

_BASE_DIR = _os.path.dirname(_os.path.abspath(__file__))

symbol_real = {

            # Grandes blue‑chips (Ibovespa e top 10)
            "VALE3.SA": "Vale ON",
            "PETR4.SA": "Petrobras PN",
            "ITUB4.SA": "Itaú Unibanco PN",
            "B3SA3.SA": "B3 ON",
            "BBAS3.SA": "Banco do Brasil ON",
            "BBDC3.SA": "Bradesco ON",
            "ABEV3.SA": "Ambev ON",
            "WEGE3.SA": "WEG ON",
            "PETR3.SA": "Petrobras ON",
            "MGLU3.SA": "Magazine Luiza ON",
            # Outros destaques top ~100 do IBrX‑100
            "SUZB3.SA": "Suzano ON",
            "GGBR4.SA": "Gerdau PN",
            "CSNA3.SA": "CSN ON",
            "BRAP4.SA": "Bradespar PN",
            "BRKM5.SA": "Braskem PNA",
            "BBDC4.SA": "Bradesco PN",
            "BBSE3.SA": "BB Seguridade ON",
            "BPAC11.SA": "BTG Pactual Units",
            "ITSA4.SA": "Itaúsa PN",
            "RADL3.SA": "Raia Drogasil ON",
            "LREN3.SA": "Lojas Renner ON",
            "RENT3.SA": "Localiza ON",
            "GOLL4.SA": "Gol PN",
            "CYRE3.SA": "Cyrela ON",
            "COGN3.SA": "Cogna ON",
            "TIMS3.SA": "Tim ON",
            "RDOR3.SA": "Rede D’Or ON",
            "CPFE3.SA": "CPFL Energia ON",
            "RAIL3.SA": "Rumo ON",
            "MRVE3.SA": "MRV ON",
            "JBSS3.SA": "JBS ON",
            "QUAL3.SA": "Qualicorp ON",
            "KLBN11.SA": "Klabin Units",
            "ENGI11.SA": "Energisa Units",
            "ELET3.SA": "Eletrobras ON",
            "ELET6.SA": "Eletrobras PNB",
            "ENBR3.SA": "EDP Brasil ON",
            "EGIE3.SA": "Engie Brasil ON",
            "SLCE3.SA": "SLC Agrícola ON",
            "TAEE11.SA": "Taesa Units",
            "AZUL4.SA": "Azul PN",
            "BEEF3.SA": "Minerva ON",
            "NATU3.SA": "Natura ON",
            "VIVT3.SA": "Telefônica Brasil ON",
            "BRFS3.SA": "BRF ON",
            "MULT3.SA": "Multiplan ON",
            "PRIO3.SA": "PetroRio ON",
            "CPLE6.SA": "Copel PNB",
            "CGAS5.SA": "Comgás PNA",
            "HYPE3.SA": "Hypera ON",
            "CSAN3.SA": "Cosan ON",
            "ENAT3.SA": "Enauta ON",
            "LWSA3.SA": "Lojas Quero-Quero ON",
            "BPAN4.SA": "Banrisul PN",
            "ALPA4.SA": "Alpargatas PN",
            "CAML3.SA": "Camil ON",
            "EMBJ3.SA": "Embraer ON",
            "CVCB3.SA": "CVC ON",
            "VVAR3.SA": "Via ON",
            "LAME4.SA": "Lame4 PN",
            "EZTC3.SA": "EZTEC ON",
            "LOGG3.SA": "Log Commercial Properties ON",
            "EQTL3.SA": "Equatorial ON",
            "FLRY3.SA": "Fleury ON",
            "IRBR3.SA": "IRB Brasil ON",
            "SMTO3.SA": "São Martinho ON",
            "SBSP3.SA": "Sabesp ON",
            "TOTS3.SA": "Totvs ON",
            "UGPA3.SA": "Ultrapar ON",
            "USIM5.SA": "Usiminas PNA",
            "VIVT4.SA": "Telefônica Brasil PN",
            "PCAR4.SA": "Pão de Açúcar ON",
            "AZZA3.SA": "Azzas 2154 ON (ex-Arezzo/Grupo Soma)",
            "ASAI3.SA": "Assaí Atacadista ON",
            "CRFB3.SA": "Carrefour Brasil ON",
            "MRFG3.SA": "Marfrig ON",
            "MOVI3.SA": "Movida ON",
            "PETZ3.SA": "Petz ON",
            "POSI3.SA": "Positivo Tecnologia ON",
            "RECV3.SA": "PetroRecôncavo ON",
            "RRRP3.SA": "3R Petroleum ON",
            "SYNE3.SA": "Syn Prop & Tech ON",
            "TRPL4.SA": "Transmissão Paulista PN",
            "UNIP6.SA": "Unipar PNB",
            "CASH3.SA": "Méliuz ON",
            "AERI3.SA": "Aeris ON",    "AMER3.SA": "Americanas ON",
            "ALOS3.SA": "Allos ON (ex-Aliansce Sonae/BR Malls)",
            "BMGB4.SA": "Banco BMG PN",
            "CEAB3.SA": "C&A ON",
            "DXCO3.SA": "Dexco ON",
            "IGTI11.SA": "Iguatemi Units",
            "JHSF3.SA": "JHSF ON",
            "LIGT3.SA": "Light ON",
            "LOGN3.SA": "Log-In Logística ON",
            "MEAL3.SA": "IMC - International Meal Company ON",
            "NGRD3.SA": "Neogrid ON",
            "PNVL3.SA": "Panvel ON",
            "SAPR11.SA": "Sanepar Units",
            "SLED4.SA": "Saraiva Livreiros PN",
            "AURE3.SA": "Auren Energia ON",
            "CXSE3.SA": "Caixa Seguridade Participações ON",
            "HBSA3.SA": "Hidrovias do Brasil ON",
            "ISAE4.SA": "ISA Energia Brasil PN",
            "SIMH3.SA": "Simpar ON",
            "TUPY3.SA": "Tupy ON",
            "OIBR3.SA": "Oi ON",
            "BRAV3.SA": "Brava Energia ON",
            "SANB11.SA": "Banco Santander (Brasil) S.A.",
            "ALUP11.SA": "Alupar Units", 
            "DIRR3.SA": "Direcional ON",
            "CMIG4.SA": "Cemig PN",
            "AXIA3.SA": "Axia Energia ON",
            "CPLE3.SA": "Copel ON",
            "MBRF3.SA": "MBRF Global Foods Company ON",

            # Complementos Ibovespa (carteira vigente na B3)
            "VBBR3.SA": "Vibra Energia ON",
            "CSMG3.SA": "Copasa ON",
            "CMIN3.SA": "CSN Mineração ON",
            "CURY3.SA": "Cury Construtora e Incorporadora ON",
            "ENEV3.SA": "Eneva ON",
            "GOAU4.SA": "Gerdau Metalúrgica PN",
            "HAPV3.SA": "Hapvida ON",
            "POMO4.SA": "Marcopolo PN",
            "MOTV3.SA": "Motiva ON (ex-CCR)",
            "PSSA3.SA": "Porto Seguro ON",
            "SMFT3.SA": "Smart Fit ON",
            "VAMO3.SA": "Vamos ON",
            "VIVA3.SA": "Vivara ON",
            "YDUQ3.SA": "YDUQS Participações ON",
            "RANI3.SA": "Irani Papel e Embalagem ON",

            # BDRs (Brazilian Depositary Receipts) — composição do índice BDRX (B3)
            "MMMC34.SA": "3M Co. (BDR)",
            "ABBV34.SA": "AbbVie Inc. (BDR)",
            "ADBE34.SA": "Adobe Inc. (BDR)",
            "A1AP34.SA": "Advance Auto Parts Inc. (BDR)",
            "A1MD34.SA": "Advanced Micro Devices Inc. (AMD) (BDR)",
            "AIRB34.SA": "Airbnb Inc. (BDR)",
            "A1LB34.SA": "Albemarle Corp. (BDR)",
            "BABA34.SA": "Alibaba Group Holding Ltd. (BDR)",
            "GOGL35.SA": "Alphabet Inc. Class C (BDR)",
            "GOGL34.SA": "Alphabet Inc. Class A (BDR)",
            "AMZO34.SA": "Amazon.com Inc. (BDR)",
            "AALL34.SA": "American Airlines Group Inc. (BDR)",
            "AXPB34.SA": "American Express Co. (BDR)",
            "T1OW34.SA": "American Tower Corp. (BDR)",
            "AAPL34.SA": "Apple Inc. (BDR)",
            "A1MT34.SA": "Applied Materials Inc. (BDR)",
            "ARMT34.SA": "ArcelorMittal S.A. (BDR)",
            "A1NE34.SA": "Arista Networks Inc. (BDR)",
            "ASML34.SA": "ASML Holding N.V. (BDR)",
            "A1ZN34.SA": "AstraZeneca plc (BDR)",
            "ATTB34.SA": "AT&T Inc. (BDR)",
            "BIDU34.SA": "Baidu Inc. (BDR)",
            "BOAC34.SA": "Bank of America Corp. (BDR)",
            "BERK34.SA": "Berkshire Hathaway Inc. (BDR)",
            "B2YN34.SA": "Beyond Meat Inc. (BDR)",
            "B1IL34.SA": "Bilibili Inc. (BDR)",
            "B2HI34.SA": "Bill Holdings Inc. (BDR)",
            "B1NT34.SA": "BioNTech SE (BDR)",
            "BLAK34.SA": "BlackRock Inc. (BDR)",
            "X1YZ34.SA": "Block Inc. (BDR)",
            "BKNG34.SA": "Booking Holdings Inc. (BDR)",
            "B1PP34.SA": "BP plc (BDR)",
            "B1TI34.SA": "British American Tobacco plc (BDR)",
            "AVGO34.SA": "Broadcom Inc. (BDR)",
            "CATP34.SA": "Caterpillar Inc. (BDR)",
            "CHVX34.SA": "Chevron Corp. (BDR)",
            "CSCO34.SA": "Cisco Systems Inc. (BDR)",
            "CTGP34.SA": "Citigroup Inc. (BDR)",
            "COCA34.SA": "Coca-Cola Co. (BDR)",
            "C2OI34.SA": "Coinbase Global Inc. (BDR)",
            "COLG34.SA": "Colgate-Palmolive Co. (BDR)",
            "COPH34.SA": "ConocoPhillips (BDR)",
            "COWC34.SA": "Costco Wholesale Corp. (BDR)",
            "C2RW34.SA": "CrowdStrike Holdings Inc. (BDR)",
            "DEEC34.SA": "Deere & Co. (BDR)",
            "D1EL34.SA": "Dell Technologies Inc. (BDR)",
            "DEOP34.SA": "Diageo plc (BDR)",
            "E1CO34.SA": "Ecopetrol S.A. (BDR)",
            "EQIX34.SA": "Equinix Inc. (BDR)",
            "E1QN34.SA": "Equinor ASA (BDR)",
            "EXXO34.SA": "Exxon Mobil Corp. (BDR)",
            "FDMO34.SA": "Ford Motor Co. (BDR)",
            "F2NV34.SA": "Franco-Nevada Corp. (BDR)",
            "GEOO34.SA": "GE Aerospace (BDR)",
            "GMCO34.SA": "General Motors Co. (BDR)",
            "GSGI34.SA": "Goldman Sachs Group Inc. (BDR)",
            "C2OL34.SA": "Grupo Cibest S.A. (ex-Bancolombia) (BDR)",
            "HOME34.SA": "Home Depot Inc. (BDR)",
            "HPQB34.SA": "HP Inc. (BDR)",
            "H1SB34.SA": "HSBC Holdings plc (BDR)",
            "ITLC34.SA": "Intel Corp. (BDR)",
            "JDCO34.SA": "JD.com Inc. (BDR)",
            "JNJB34.SA": "Johnson & Johnson (BDR)",
            "JPMC34.SA": "JPMorgan Chase & Co. (BDR)",
            "K2CG34.SA": "Kingsoft Cloud Holdings Ltd. (BDR)",
            "KHCB34.SA": "Kraft Heinz Co. (BDR)",
            "LILY34.SA": "Eli Lilly and Co. (BDR)",
            "L1YG34.SA": "Lloyds Banking Group plc (BDR)",
            "L1MN34.SA": "Lumen Technologies Inc. (BDR)",
            "MSCD34.SA": "Mastercard Inc. (BDR)",
            "MCDC34.SA": "McDonald's Corp. (BDR)",
            "M2PT34.SA": "Medical Properties Trust Inc. (BDR)",
            "MELI34.SA": "MercadoLibre Inc. (BDR)",
            "MRCK34.SA": "Merck & Co. Inc. (BDR)",
            "M1TA34.SA": "Meta Platforms Inc. (BDR)",
            "MUTC34.SA": "Micron Technology Inc. (BDR)",
            "MSFT34.SA": "Microsoft Corp. (BDR)",
            "M1RN34.SA": "Moderna Inc. (BDR)",
            "M1NS34.SA": "Monster Beverage Corp. (BDR)",
            "MSBR34.SA": "Morgan Stanley (BDR)",
            "N1DA34.SA": "Nasdaq Inc. (BDR)",
            "NFLX34.SA": "Netflix Inc. (BDR)",
            "N1EM34.SA": "Newmont Corp. (BDR)",
            "NEXT34.SA": "NextEra Energy Inc. (BDR)",
            "NIKE34.SA": "Nike Inc. (BDR)",
            "N1VO34.SA": "Novo Nordisk A/S (BDR)",
            "ROXO34.SA": "Nu Holdings Ltd. (BDR)",
            "NVDC34.SA": "NVIDIA Corp. (BDR)",
            "OXYP34.SA": "Occidental Petroleum Corp. (BDR)",
            "ORCL34.SA": "Oracle Corp. (BDR)",
            "PAGS34.SA": "PagSeguro Digital Ltd. (BDR)",
            "P2LT34.SA": "Palantir Technologies Inc. (BDR)",
            "P2AN34.SA": "Palo Alto Networks Inc. (BDR)",
            "PYPL34.SA": "PayPal Holdings Inc. (BDR)",
            "P1DD34.SA": "PDD Holdings Inc. (BDR)",
            "PEPB34.SA": "PepsiCo Inc. (BDR)",
            "PFIZ34.SA": "Pfizer Inc. (BDR)",
            "PGCO34.SA": "Procter & Gamble Co. (BDR)",
            "P1LD34.SA": "Prologis Inc. (BDR)",
            "QCOM34.SA": "Qualcomm Inc. (BDR)",
            "R1IN34.SA": "Realty Income Corp. (BDR)",
            "RIOT34.SA": "Rio Tinto plc (BDR)",
            "R2BL34.SA": "Roblox Corp. (BDR)",
            "SSFO34.SA": "Salesforce Inc. (BDR)",
            "BCSA34.SA": "Banco Santander S.A. (BDR)",
            "S2EA34.SA": "Sea Ltd. (BDR)",
            "N1OW34.SA": "ServiceNow Inc. (BDR)",
            "S2HO34.SA": "Shopify Inc. (BDR)",
            "S1BS34.SA": "Sibanye Stillwater Ltd. (BDR)",
            "S2GM34.SA": "Sigma Lithium Corp. (BDR)",
            "SIMN34.SA": "Simon Property Group Inc. (BDR)",
            "S2NW34.SA": "Snowflake Inc. (BDR)",
            "S2ED34.SA": "SolarEdge Technologies Inc. (BDR)",
            "S1PO34.SA": "Spotify Technology S.A. (BDR)",
            "S2TA34.SA": "STAG Industrial Inc. (BDR)",
            "STOC34.SA": "StoneCo Ltd. (BDR)",
            "M2ST34.SA": "Strategy Inc. (ex-MicroStrategy) (BDR)",
            "TSMC34.SA": "Taiwan Semiconductor Manufacturing Co. (BDR)",
            "T1TW34.SA": "Take-Two Interactive Software Inc. (BDR)",
            "T1AL34.SA": "TAL Education Group (BDR)",
            "T2DH34.SA": "Teladoc Health Inc. (BDR)",
            "TSLA34.SA": "Tesla Inc. (BDR)",
            "TMOS34.SA": "Thermo Fisher Scientific Inc. (BDR)",
            "TMCO34.SA": "Toyota Motor Corp. (BDR)",
            "T2TD34.SA": "The Trade Desk Inc. (BDR)",
            "RIGG34.SA": "Transocean Ltd. (BDR)",
            "U1BE34.SA": "Uber Technologies Inc. (BDR)",
            "UNHH34.SA": "UnitedHealth Group Inc. (BDR)",
            "U2ST34.SA": "Unity Software Inc. (BDR)",
            "U2PS34.SA": "Upstart Holdings Inc. (BDR)",
            "VERZ34.SA": "Verizon Communications Inc. (BDR)",
            "VISA34.SA": "Visa Inc. (BDR)",
            "V1OD34.SA": "Vodafone Group plc (BDR)",
            "WALM34.SA": "Walmart Inc. (BDR)",
            "DISB34.SA": "Walt Disney Co. (BDR)",
            "WFCO34.SA": "Wells Fargo & Co. (BDR)",

            # Câmbio
            "USDBRL=X": "Dólar Americano (USD/BRL)",

            # Índices de Ações Brasil
            "BOVA11.SA": "iShares Ibovespa ETF (Equities)",
            "BRAX11.SA": "iShares IBrX-100 ETF (Equities)",
            "SMAL11.SA": "iShares Small Cap ETF (Equities)",
            "ISUS11.SA": "iShares S&P 500 USD Hedge (Equities)",
            "IVVB11.SA": "iShares S&P 500 ETF (Equities)",

            # Setoriais
            "FIND11.SA": "iShares Financials ETF (Equities)",
            "MATB11.SA": "iShares Basic Materials ETF (Equities)",
            "IMOB11.SA": "iShares Real Estate ETF (Equities)",

            # ESG / Temáticos
            "ESGB11.SA": "iShares ESG Brasil ETF (Equities)",
            "GOVE11.SA": "Trend Governance ESG ETF (Equities)",

            # Fundos internacionais
            "XINA11.SA": "Trend China ETF (Equities)",
            "EURP11.SA": "Trend Europe ETF (Equities)",
            "JAPN11.SA": "Trend Japan ETF (Equities)",
            "ASIA11.SA": "Trend Asia ETF (Equities)",
            "ETHE11.SA": "Hashdex Ethereum ETF (Crypto)",
            "HASH11.SA": "Hashdex Nasdaq Crypto Index ETF (Crypto)",
            "BITH11.SA": "Bitcoin Futures ETF – Hashdex (Crypto)",

            # Renda fixa e proteção
            "FIXA11.SA": "Trend Renda Fixa Imediata ETF (Fixed Income)",
            "IMAB11.SA": "iShares Índice de Títulos Públicos (Fixed Income)",
            "IRFM11.SA": "iShares Índice de Renda Fixa de Mercado (Fixed Income)",
            "B5P211.SA": "It Now IMA-B5 P2 Fundo De Indice (Fixed Income)",
            "TIPB11.SA": "Trend Inflação Longa ETF (Fixed Income)",
            "GOLD11.SA": "Trend Ouro (Commodities)",

            # Imobiliário (IFIX)
            "XFIX11.SA": "Trend IFIX ETF (REITs)",
            
            "NUCL11.SA": "Investo MVIS Global Uranium & Nuclear Energy ETF Fundo De Indice",
            "GPUS11.SA": "Investo Gp Etf S&P 500 Fundo De Indice",
            "WRLD11.SA": "Investo Ftse Global Equities Etf Fundo de Investimento de Indice Investimento Exterior",
            "BIZD11.SA": "Investo Mvsis US Businesss Development Companies Index ETF Fundo de Indice",
            "GLDX11.SA": "Investo ETF Solactive Gold Spot Index Fundo de Indice",
            "LFTB11.SA": "Investo ETF Marketvector Brazil Treasury 760 Day Target Duration Classe de Indice",
            "HODL11.SA": "Investo ETF Marketvector Bitcoin Benchmark Rate Fundo de Indice",
            "CHIP11.SA": "Investo Etf Bluestar 5G Communications Index Fundo de Indice",
            "NTNS11.SA": "Investo Texa Tesouro Ipca+ 0 a 4 anos ETF Fundo de Investimento de Indice",
            "LFTS11.SA": "Investo Teva Tesouro Selic ETF -Fundo de Investimento de Indice",
            "USTK11.SA": "Investo ETF MSCI US Technology Fundo De Investimento De Indice – Investimento No Exterior",
            "ALUG11.SA": "Investo Msci US Real Estate ETF Fundo De Investimento De Indice Investimento Exterior",
            "JOGO11.SA": "Investo Etf Global Video Gaming & Esports Fundo De Investimento De Indice",
            "BDOM11.SA": "Investo Marketvector Brazil Domestic Exposure Etf - Fundo De Investimento De Indice",
            "BXPO11.SA": "Investo Marketvector Brazil Global Exposure Etf – Fundo De Investimento De Indice",
            "SCVB11.SA": "Investo Marketvector Brazil Small Cap Value Etf - Fundo De Investimento De Indice",
            "SVAL11.SA": "Investo ETF S&P Smallcap 600 Value Fundo de Investimento de Índice",
            "SPXI11.SA": "BTG Pactual S&P 500 Fundo de Índice (Equities)",
            "NASD11.SA": "Trend Nasdaq 100 ETF (Equities)",
            "DIVO11.SA": "It Now IDIV Fundo de Índice (Equities)",
            "ECOO11.SA": "iShares Índice Carbono Eficiente ETF (Equities)",
            "SMAC11.SA": "It Now Small Cap Fundo de Índice (Equities)",
            "TECK11.SA": "ETF de Tecnologia (Equities)",

            # Mais ETFs negociados na B3
            "SPYI11.SA": "Buena Vista US High Income ETF (Equities)",
            "BBOV11.SA": "BB ETF Ibovespa Fundo de Índice (Equities)",
            "NDIV11.SA": "Nu Ibovespa Smart Dividendos ETF (Equities)",
            "QQQI11.SA": "Buena Vista Nasdaq-100 High Income ETF (Equities)",
            "SPXB11.SA": "BTG Pactual S&P 500 BRL Fundo de Índice (Equities)",
            "COIN11.SA": "Buena Vista Neos Bitcoin High Income ETF (Crypto)",
            "DIVD11.SA": "It Now IDIV Fundo de Índice (Equities)",
            "QBTC11.SA": "QR CME CF Bitcoin Reference Rate ETF (Crypto)",
            "AUVP11.SA": "BTG Pactual Teva Ações Fundamentos Fundo de Índice (Equities)",
            "AUPO11.SA": "BTG Pactual Teva AUVP ITBR Liquidez Fundo de Índice (Fixed Income)",
            "BBSD11.SA": "BB ETF S&P Dividendos Brasil Fundo de Índice (Equities)",
            "BEST11.SA": "BTG Pactual MarketVector BESST Quality ETF (Equities)",
            "AREA11.SA": "BTG Pactual Teva ITBR IPCA Rendimento Fundo de Índice (Fixed Income)",
            "IWMI11.SA": "Buena Vista Neos Russell 2000 High Income ETF (Equities)",
            "BOVV11.SA": "It Now Ibovespa Fundo de Índice (Equities)",
            "BOVB11.SA": "Bradesco ETF Ibovespa Fundo de Índice (Equities)",
            "CRPT11.SA": "Empiricus Cripto Top 20 ETF (Crypto)",
            "LVOL11.SA": "Nu Ibovespa Smart Low Volatility ETF (Equities)",
            "XBOV11.SA": "Caixa ETF Ibovespa Fundo de Índice (Equities)",
            "GPCA11.SA": "Grão Teva ITBR Tesouro IPCA 2 Anos Fundo de Índice (Fixed Income)",
            "ACWI11.SA": "Trend ETF MSCI ACWI Fundo de Índice (Equities)",
            "CASA11.SA": "Buena Vista US Real Estate High Income ETF (REITs)"
            }

symbol_dolar = {
                "GSLC": "Goldman Sachs ActiveBeta U.S. Large Cap Equity ETF (Equities)",
                "VOO": "Vanguard S&P 500 ETF (Equities)",
                "QQQ": "Invesco QQQ Trust (Equities)",
                "IVV": "S&P 500 Core ETF (Equities)",
                "DHS": "US High Dividend ETF (Equities)",
                "AOK": "Conservative Allocation ETF (Multi-Asset)",
                "QQQM": "NASDAQ 100 ETF (Equities)",
                "EEMA": "EM Asia ETF (Equities)",
                "VEA": "Developed Markets ETF (Equities)",
                "HEEM": "iShares Currency Hedged MSCI Emerging Markets ETF (Equities)",
                "VIG": "Dividend Appreciation ETF (Equities)",
                "VYM": "High Dividend Yield ETF (Equities)",
                "VYMI": "Vanguard International High Dividend Yield ETF (Equities)",
                "SPY": "S&P 500 (Equities)",
                "VTI": "Vanguard Total Stock Market ETF (Equities)",
                "VT": "Vanguard Total World Stock ETF (Equities)",
                "VO": "Vanguard Mid-Cap ETF (Equities)",
                "VB": "Vanguard Small-Cap ETF (Equities)",
                "IWM": "iShares Russell 2000 ETF (Equities)",
                "DIA": "SPDR Dow Jones Industrial Average ETF (Equities)",
                "SPLG": "SPDR Portfolio S&P 500 ETF (Equities)",
                "EFA": "MSCI EAFE Developed Markets ETF (Equities)",
                "EWZ": "iShares MSCI Brazil ETF (Equities)",
                "FXI": "iShares China Large-Cap ETF (Equities)",
                "EWJ": "iShares MSCI Japan ETF (Equities)",
                "INDA": "iShares MSCI India ETF (Equities)",
                "EWW": "iShares MSCI Mexico ETF (Equities)",
                "AFK": "VanEck Africa Index ETF (Equities)",
                "FM": "iShares Frontier and Select EM ETF (Equities)",
                "FRN": "Invesco Frontier Markets ETF (Equities)",
                "ILF": "iShares Latin America 40 ETF (Equities)",
                "ECH": "iShares MSCI Chile ETF (Equities)",
                "EPU": "iShares MSCI Peru ETF (Equities)",
                "GXG": "Global X MSCI Colombia ETF (Equities)",
                "VNM": "VanEck Vietnam ETF (Equities)",
                "THD": "iShares MSCI Thailand ETF (Equities)",
                "EPHE": "iShares MSCI Philippines ETF (Equities)",
                "EIDO": "iShares MSCI Indonesia ETF (Equities)",
                "GULF": "WisdomTree Middle East Dividend ETF (Equities)",
                "MES": "Market Vectors Gulf States ETF (Equities)",
                "VTV": "Vanguard Value ETF (Equities)",
                "VUG": "Vanguard Growth ETF (Equities)",
                "VOE": "Vanguard Mid-Cap Value ETF (Equities)",
                "VBR": "Vanguard Small-Cap Value ETF (Equities)",
                "IVW": "iShares S&P 500 Growth ETF (Equities)",
                "IVE": "iShares S&P 500 Value ETF (Equities)",
                "IJH": "iShares Core S&P Mid-Cap ETF (Equities)",
                "IJR": "iShares Core S&P Small-Cap ETF (Equities)",
                "IUSG": "iShares Core S&P U.S. Growth ETF (Equities)",
                "IUSV": "iShares Core S&P U.S. Value ETF (Equities)",
                "ACWI": "iShares MSCI ACWI ETF (Equities)",
                "IOO": "iShares Global 100 ETF (Equities)",
                "RSP": "Invesco S&P 500 Equal Weight ETF (Equities)",
                "MTUM": "iShares MSCI USA Momentum Factor ETF (Equities)",
                "USMV": "iShares MSCI USA Min Vol Factor ETF (Equities)",
                "QUAL": "iShares MSCI USA Quality Factor ETF (Equities)",
                "VLUE": "iShares MSCI USA Value Factor ETF (Equities)",
                "EEM": "iShares MSCI Emerging Markets ETF (Equities)",
                "SCHP": "US TIPS ETF (Fixed Income)",
                "TFLO": "iShares Treasury Floating Rate Bond ETF (Fixed Income)",
                "SLQD": "iShares 0-5 Year Investment Grade Corporate Bond ETF (Fixed Income)",
                "TLT": "20+ Year Treasury Bond ETF (Fixed Income)",
                "BNDX": "Int'l Bond ETF (Fixed Income)",
                "IEF": "7-10Y Treasury Bond (Fixed Income)",
                "GOVT": "US Government Bond (Fixed Income)",
                "LQD": "Investment Grade Corporate Bond (Fixed Income)",
                "USHY": "US High Yield Bond (Fixed Income)",
                "USFR": "Floating Rate Treasury (Fixed Income)",
                "SHY": "1-3 Year Treasury Bond ETF (Fixed Income)",
                "BND": "Total Bond Market ETF (Fixed Income)",
                "TIP": "TIPS Bond ETF (Fixed Income)",
                "HYG": "High Yield Corporate Bond ETF (Fixed Income)",
                "MUB": "National Muni Bond ETF (Fixed Income)",
                "EMB": "Emerging Markets USD Bond ETF (Fixed Income)",
                "VCIT": "Intermediate-Term Corporate Bond ETF (Fixed Income)",
                "VCSH": "Short-Term Corporate Bond ETF (Fixed Income)",
                "TFI": "SPDR Nuveen Municipal Bond ETF (Fixed Income)",
                "HYD": "High-Yield Muni Bond ETF (Fixed Income)",
                "SPSB": "Short-Term Investment Grade Bond ETF (Fixed Income)",
                "BSV": "Short-Term Bond ETF (Fixed Income)",
                "IGOV": "International Treasury Bond ETF (Fixed Income)",
                "BWX": "International Govt Bond ETF ex-US (Fixed Income)",
                "SGOV": "1-3 Month US Treasury ETF (Fixed Income)",
                "BIL": "SPDR Bloomberg 1-3 Month T-Bill ETF (Fixed Income)",
                "GLD": "Gold ETF (Commodities)",
                "GDX": "Gold Miners ETF (Commodities)",
                "IAU": "iShares Gold Trust (Commodities)",
                "SLV": "Silver Trust (Commodities)",
                "USO": "US Oil Fund (Commodities)",
                "PDBC": "Diversified Commodities (Commodities)",
                "DBC": "Commodities Index Tracking ETF (Commodities)",
                "CPER": "US Copper Index Fund (Commodities)",
                "DBA": "Agriculture Fund ETF (Commodities)",
                "TQQQ": "UltraPro QQQ (Leveraged/Inverse)",
                "SQQQ": "UltraPro Short QQQ (Leveraged/Inverse)",
                "SPXS": "UltraShort S&P500 (Leveraged/Inverse)",
                "UVXY": "VIX Short-Term Futures (Leveraged/Inverse)",
                "UPRO": "UltraPro S&P 500 (Leveraged/Inverse)",
                "SDOW": "UltraPro Short Dow30 (Leveraged/Inverse)",
                "TZA": "Small Cap Bear 3x Shares (Leveraged/Inverse)",
                "FNGU": "FANG+ 3X Leveraged ETN (Leveraged/Inverse)",
                "DOC": "Physicians Realty (REITs)",
                "FRT": "Federal Realty (REITs)",
                "SLG": "SL Green Realty (REITs)",
                "O": "Realty Income (REITs)",
                "VNQ": "Vanguard Real Estate ETF (REITs)",
                "SCHH": "Schwab U.S. REIT ETF (REITs)",
                "IYR": "iShares U.S. Real Estate ETF (REITs)",
                "SOXX": "Semiconductor ETF (Thematic)",
                "SMH": "VanEck Semiconductor ETF (Thematic)",
                "XLK": "Technology Sector ETF (Thematic)",
                "XLV": "Healthcare Sector ETF (Thematic)",
                "XLY": "Consumer Discretionary ETF (Thematic)",
                "XHB": "Homebuilders ETF (Thematic)",
                "XAR": "SPDR S&P Aerospace & Defense ETF (Thematic)",
                "XAR": "Aerospace & Defense ETF (Thematic)",
                "REZ": "Residential & Healthcare REIT ETF (Thematic)",
                "ARKK": "ARK Innovation ETF (Thematic)",
                "QYLD": "Nasdaq-100 Covered Call (Thematic)",
                "SCHD": "US Dividend Equity (Thematic)",
                "XLF": "Financials Sector (Thematic)",
                "XLI": "Industrials Sector (Thematic)",
                "XLE": "Energy Sector (Thematic)",
                "XLU": "Utilities Sector (Thematic)",
                "IDU": "iShares U.S. Utilities ETF (Thematic)",
                "XLP": "Consumer Staples (Thematic)",
                "XBI": "S&P Biotech ETF (Thematic)",
                "BTC-USD": "Bitcoin (USD)",
                "BITO": "ProShares Bitcoin Strategy ETF (Crypto)",
                "GBTC": "Grayscale Bitcoin Trust (Crypto)",
                "ETHE": "Grayscale Ethereum Trust (Crypto)",
                "IBIT": "iShares Bitcoin Trust (Crypto)",
                "FBTC": "Fidelity Wise Origin Bitcoin Fund (Crypto)",
                "ARKB": "ARK 21Shares Bitcoin ETF (Crypto)",
                "FXE": "Invesco CurrencyShares Euro Trust (Currency)",
                "FXY": "Invesco CurrencyShares Japanese Yen Trust (Currency)",
                "FXF": "Invesco CurrencyShares Swiss Franc Trust (Currency)",
                "FXB": "Invesco CurrencyShares British Pound Trust (Currency)",
                "FXC": "Invesco CurrencyShares Canadian Dollar Trust (Currency)",
                "FXA": "Invesco CurrencyShares Australian Dollar Trust (Currency)",
                "CYB": "WisdomTree Chinese Yuan Strategy Fund (Currency)",
                "UUP": "US Dollar Index Bullish ETF (Currency)",
                "UDN": "US Dollar Index Bearish ETF (Currency)",
                "DBV": "Invesco DB G10 Currency Harvest Fund (Currency)",
                "VXX": "S&P 500 VIX Short-Term Futures ETN (Volatility)",
                "AAPL": "Apple Inc.",
                "MSFT": "Microsoft Corp.",
                "NVDA": "Nvidia Corp.",
                "GOOGL": "Alphabet Inc. (Class A)",
                "AMZN": "Amazon.com Inc.",
                "JPM": "JPMorgan Chase & Co.",
                "PG": "Procter & Gamble Co.",
                "UNH": "UnitedHealth Group Inc.",
                "V": "Visa Inc.",
                "MA": "Mastercard Inc.",
                "HD": "Home Depot, Inc.",
                "DIS": "Walt Disney Co.",
                "INTC": "Intel Corp.",
                "CSCO": "Cisco Systems, Inc.",
                "XOM": "Exxon Mobil Corp.",
                "CVX": "Chevron Corp.",
                "KO": "Coca‑Cola Co.",
                "PEP": "PepsiCo, Inc.",
                "VZ": "Verizon Communications",
                # Mega‑caps adicionais
                "TSM": "Taiwan Semiconductor (ADR)",
                "ADBE": "Adobe Inc.",
                "ABBV": "AbbVie Inc.",
                "COST": "Costco Wholesale Corp.",
                "BAC": "Bank of America Corp.",
                "CRM": "Salesforce Inc.",
                "MCD": "McDonald's Corp.",
                "ORCL": "Oracle Corp.",
                "TXN": "Texas Instruments Inc.",
                "QCOM": "Qualcomm Inc.",
                "BA": "Boeing Co.",
                "GS": "Goldman Sachs Group Inc.",
                "GE": "General Electric Co.",
                "NKE": "Nike Inc.",
                "SBUX": "Starbucks Corp.",
                "AMD": "Advanced Micro Devices Inc.",
                "INTU": "Intuit Inc.",
                "ISRG": "Intuitive Surgical Inc.",
                "NOW": "ServiceNow Inc.",
                "AMAT": "Applied Materials Inc.",
                "BKNG": "Booking Holdings Inc.",
                "MDLZ": "Mondelez International Inc.",
                "ADI": "Analog Devices Inc.",
                "VRTX": "Vertex Pharmaceuticals Inc.",
                "REGN": "Regeneron Pharmaceuticals Inc.",
                "FDX": "FedEx Corp.",
                "MRNA": "Moderna Inc.",
                "LRCX": "Lam Research Corp.",
                "MO": "Altria Group Inc.",
                "DE": "Deere & Co.",
                "T": "AT&T Inc.",
                "F": "Ford Motor Co.",
                "GM": "General Motors Co.",
                "WBA": "Walgreens Boots Alliance Inc.",
                "MET": "MetLife Inc.",
                "PNC": "PNC Financial Services Group Inc.",
                "USB": "U.S. Bancorp",
                "SO": "Southern Co.",
                "D": "Dominion Energy Inc.",
                "AEP": "American Electric Power Co.",
                "EOG": "EOG Resources Inc.",
                "PSX": "Phillips 66",
                "MPC": "Marathon Petroleum Corp.",
                "PLD": "Prologis Inc.",
                "SPGI": "S&P Global Inc.",
                "ICE": "Intercontinental Exchange Inc.",
                "TGT": "Target Corp.",
                "LOW": "Lowe's Companies Inc.",
                "BK": "Bank of New York Mellon Corp.",
                "CTAS": "Cintas Corp.",
                "AIG": "American International Group Inc.",
                "C": "Citigroup Inc.",
                "ALL": "Allstate Corp.",
                "MS": "Morgan Stanley",
                "SCHW": "Charles Schwab Corp.",
                "EBAY": "eBay Inc.",
                "ZM": "Zoom Video Communications Inc.",
                "PYPL": "PayPal Holdings Inc.",
                "ROKU": "Roku Inc.",
                "SNOW": "Snowflake Inc.",
                "ABNB": "Airbnb Inc.",
                "LYFT": "Lyft Inc.",
                "UBER": "Uber Technologies Inc.",
                "RBLX": "Roblox Corp.",
                "BIDU": "Baidu Inc. (ADR)",
                "JD": "JD.com Inc. (ADR)",
                "PDD": "PDD Holdings Inc. (ADR)",
                "BABA": "Alibaba Group Holding Ltd. (ADR)",
                "ADP": "Automatic Data Processing Inc.",
                "MNST": "Monster Beverage Corp.",
                "AFL": "Aflac Inc.",
                "CME": "CME Group Inc.",
                "EL": "Estée Lauder Companies Inc.",
                "HCA": "HCA Healthcare Inc.",
                "BIIB": "Biogen Inc.",
                "AZO": "AutoZone Inc.",
                "ORLY": "O'Reilly Automotive Inc.",
                "TT": "Trane Technologies plc",
                "FTNT": "Fortinet Inc.",
                "CDNS": "Cadence Design Systems Inc.",
                "ANET": "Arista Networks Inc.",
                "ENPH": "Enphase Energy Inc.",
                "FSLR": "First Solar Inc.",
                "TTD": "The Trade Desk Inc.",
                "ZS": "Zscaler Inc.",
                "CRWD": "CrowdStrike Holdings Inc.",
                "DDOG": "Datadog Inc.",
                "OKTA": "Okta Inc.",
                "MDB": "MongoDB Inc.",
                "TEAM": "Atlassian Corp.",
                "DOCU": "DocuSign Inc.",
                "ROST": "Ross Stores Inc.",
                "DLTR": "Dollar Tree Inc.",
                "DG": "Dollar General Corp.",
                "WBD": "Warner Bros. Discovery Inc.",
                "PARA": "Paramount Global",
                "FOXA": "Fox Corp. Class A",
                "LCID": "Lucid Group Inc.",
                "RIVN": "Rivian Automotive Inc.",
                "NKLA": "Nikola Corp.",
                "XOM": "Exxon Mobil Corp.",
                "CVX": "Chevron Corp.",
                "COP": "ConocoPhillips",
                "HAL": "Halliburton Co.",
                "SLB": "Schlumberger NV",
                "MRO": "Marathon Oil Corp.",
                "APA": "APA Corp.",
                "OXY": "Occidental Petroleum Corp.",
                "ADM": "Archer-Daniels-Midland Co.",
                "KHC": "Kraft Heinz Co.",
                "KR": "Kroger Co.",
                "PEP": "PepsiCo Inc.",
                "KO": "Coca-Cola Co.",
                "CL": "Colgate-Palmolive Co.",
                "PG": "Procter & Gamble Co.",
                "MDT": "Medtronic plc",
                "SYK": "Stryker Corp.",
                "BSX": "Boston Scientific Corp.",
                "BDX": "Becton Dickinson & Co.",
                "ZBH": "Zimmer Biomet Holdings Inc.",
                "META": "Meta Platforms Inc.",
                "JPM": "JPMorgan Chase & Co.",
                "NVO": "Novo Nordisk A/S",
                "TSLA": "Tesla Inc. (Equities)",
                "AGG": "iShares Core U.S. Aggregate Bond ETF (Fixed Income)",
                "VWO": "Vanguard FTSE Emerging Markets ETF (Equities)",
                "VGT": "Vanguard Information Technology ETF (Thematic)",
                "IWF": "iShares Russell 1000 Growth ETF (Equities)",
                "VXUS": "Vanguard Total International Stock ETF (Equities)",
                "BRK-B": "Berkshire Hathaway Inc. Class B (Equities)",
                "WMT": "Walmart Inc. (Equities)",
                "AVGO": "Broadcom Inc. (Equities)",
                "LLY": "Eli Lilly and Co. (Equities)",
                "CAT": "Caterpillar Inc. (Equities)",
                "SCHX": "Schwab U.S. Large-Cap ETF (Equities)",
                "SCHB": "Schwab U.S. Broad Market ETF (Equities)",
                "VXF": "Vanguard Extended Market ETF (Equities)",
                "MDY": "SPDR S&P MidCap 400 ETF Trust (Equities)",
                "VEU": "Vanguard FTSE All-World ex-US ETF (Equities)",
                "IXUS": "iShares Core MSCI Total International Stock ETF (Equities)",
                "IEFA": "iShares Core MSCI EAFE ETF (Equities)",
                "IEMG": "iShares Core MSCI Emerging Markets ETF (Equities)",
                "MBB": "iShares MBS ETF (Fixed Income)",
                "BNDW": "Vanguard Total World Bond ETF (Fixed Income)",
                "JPST": "JPMorgan Ultra-Short Income ETF (Fixed Income)",
                "SHV": "iShares Short Treasury Bond ETF (Fixed Income)",
                "VGSH": "Vanguard Short-Term Treasury ETF (Fixed Income)",
                "VGIT": "Vanguard Intermediate-Term Treasury ETF (Fixed Income)",
                "IGLB": "iShares 10+ Year Investment Grade Corporate Bond ETF (Fixed Income)",
                "JNK": "SPDR Bloomberg High Yield Bond ETF (Fixed Income)",
                "REET": "iShares Global REIT ETF (REITs)",
                "VNQI": "Vanguard Global ex-U.S. Real Estate ETF (REITs)",
                "XLC": "Communication Services Select Sector SPDR Fund (Thematic)",
                "XLB": "Materials Select Sector SPDR Fund (Thematic)",
                "XME": "SPDR S&P Metals & Mining ETF (Thematic)",
                "ITA": "iShares U.S. Aerospace & Defense ETF (Thematic)",
                "IGV": "iShares Expanded Tech-Software Sector ETF (Thematic)",
                "FDN": "First Trust Dow Jones Internet Index Fund (Thematic)",
                "CLOU": "Global X Cloud Computing ETF (Thematic)",
                "BOTZ": "Global X Robotics & Artificial Intelligence ETF (Thematic)",
                "ARKQ": "ARK Autonomous Technology & Robotics ETF (Thematic)",
                "ICLN": "iShares Global Clean Energy ETF (Thematic)",
                "TAN": "Invesco Solar ETF (Thematic)",
                "LIT": "Global X Lithium & Battery Tech ETF (Thematic)",
                "URA": "Global X Uranium ETF (Thematic)",
                "PAVE": "Global X U.S. Infrastructure Development ETF (Thematic)",
                "SKYY": "First Trust Cloud Computing ETF (Thematic)",
                "LIN": "Linde plc (Equities)",
                "AXP": "American Express Co. (Equities)",
                "HON": "Honeywell International Inc. (Equities)",
                "PM": "Philip Morris International Inc. (Equities)",
                "UNP": "Union Pacific Corp. (Equities)",
                "CVS": "CVS Health Corp. (Equities)",
                "RTX": "RTX Corp. (Equities)",
                "LMT": "Lockheed Martin Corp. (Equities)",
                "AMGN": "Amgen Inc. (Equities)",
                "MRK": "Merck & Co. Inc. (Equities)",
                "PFE": "Pfizer Inc. (Equities)",
                "ACN": "Accenture plc (Equities)",
                "PANW": "Palo Alto Networks Inc. (Equities)",
                "MU": "Micron Technology Inc. (Equities)",
                "MELI": "MercadoLibre Inc. (Equities)",
                "SHOP": "Shopify Inc. (Equities)",
                "ARM": "Arm Holdings plc ADR (Equities)",
                "NFLX": "Netflix Inc. (Equities)",
                "GOOG": "Alphabet Inc. Class C (Equities)"
                }

symbol_euro = {
                "IWDA.AS": "iShares MSCI World (Equities)",
                "EIMI.L": "iShares Emerging Markets IMI (Equities)",
                "IMEU.L": "iShares MSCI Europe (Equities)",
                "MVOL.L": "MSCI Europe Min Volatility (Equities)",
                "EQQQ.DE": "NASDAQ 100 UCITS (Equities)",
                "EQQQ.L": "NASDAQ 100 UCITS GBP (Equities)",
                "IWMO.L": "MSCI World Minimum Volatility (Equities)",
                "SPY5.DE": "SPDR S&P 500 UCITS (Equities)",
                "XCHA.DE": "MSCI China A (Equities)",
                "XFFE.MI": "FTSE MIB (Equities)",
                "IBGS.L": "UK Gilts All Stocks (Fixed Income)",
                "IEAC.L": "Euro Corporate Bonds (Fixed Income)",
                "AGGH.L": "Global Aggregate Bond (Fixed Income)",
                "EXX6.DE": "iShares eb.rexx Government Germany 10.5+yr (Fixed Income)",
                "EXVM.DE": "iShares eb.rexx Government Germany 0-1yr (Fixed Income)",
                "IBCX.DE": "iShares Euro Government Bond 3-5yr (Fixed Income)",
                "IBGX.DE": "iShares Euro Government Bond 7-10yr (Fixed Income)",
                "IBCY.DE": "iShares Euro Government Bond 15-30yr (Fixed Income)",
                "SXR8.DE": "iShares Euro Investment Grade Corp Bond (Fixed Income)",
                "EUNA.DE": "Lyxor Euro Government Bond 10Y DR ETF (Fixed Income)",
                "IBCI.DE": "iShares Euro Government Inflation-Linked Bond ETF (Fixed Income)",
                "AGGE.DE": "iShares Global Aggregate Bond EUR Hedged (Fixed Income)",
                "BTCE.DE": "21Shares Bitcoin ETP (Crypto)",
                "ABTC.DE": "ETC Group Physical Bitcoin (Crypto)",
                "VBTC.AS": "VanEck Bitcoin ETN (Crypto)",
                "BTCE.AS": "BTCetc Bitcoin Exchange Traded Crypto (Crypto)",
                "XDWD.DE": "Xtrackers MSCI World UCITS ETF 1C (Equities)",
                "XDWD.L": "Xtrackers MSCI World UCITS ETF 1C (Equities, LSE)",
                "XMME.DE": "Xtrackers MSCI Emerging Markets UCITS ETF 1C (Equities)",
                "XMME.L": "Xtrackers MSCI Emerging Markets UCITS ETF 1C (Equities, LSE)",
                "XDWT.DE": "Xtrackers MSCI World Information Technology UCITS ETF (Thematic)",
                "XDEQ.DE": "Xtrackers MSCI World Quality UCITS ETF",
                "XZEM.DE": "Xtrackers MSCI Emerging Markets ESG UCITS ETF",
                "XWLD.L": "Xtrackers MSCI Europe UCITS ETF 1C",
                "NEAR": "iShares Short Duration Bond Active ETF (Fixed Income)",
                "IGSB": "iShares 1–5 Year Investment Grade Corporate Bond ETF (Fixed Income)",
                
                # Europa fatores & estilo
                "DBX0FK.DE": "Xtrackers MSCI Europe Value UCITS ETF",
                "DBXA.DE": "Xtrackers MSCI Europe UCITS ETF 1C",
                "DBEU.DE": "Xtrackers MSCI Europe Hedged Equity ETF",

                # Setoriais europeus
                "DBXD.DE": "Xtrackers DAX UCITS ETF 1C",
                "FEZ.L": "SPDR EURO STOXX 50 UCITS ETF",
                "ISF.L": "iShares Core FTSE 100 UCITS ETF",
                "EQS1.DE": "iShares Core DAX UCITS ETF",

                # Temáticos / fatores defensivos
                "DFND.L": "iShares STOXX Europe 600 ETF",
                "DBXS.DE": "Xtrackers Short DAX x2 Daily Swap ETF",
                "DBX0B6.DE": "Xtrackers S&P 500 2x Inverse UCITS ETF",
                "DBX0V7.DE": "Xtrackers MSCI Europe ESG ETF",

                # Imobiliário europeu
                "EPRA.L": "iShares EPRA NAREIT Europe UCITS ETF",
                "WCHG.DE": "iShares European Property Yield UCITS ETF",

                # Defensivos/dividendos
                "IEUR.DE": "iShares Core MSCI Europe Dividend UCITS",
                "BNK.DE": "Amundi STOXX Europe 600 Banks UCITS ETF",
                "ENUE.DE": "iShares MSCI Europe Financials Screened UCITS ETF",

                # Commodity / ouro ETC
                "SGLN.L": "iShares Physical Gold ETC",
                "PHAG.DE": "WisdomTree Physical Gold ETC EUR",

                # Criptomoedas
                "DFNG.L": "VanEck Europe Defence UCITS ETF",  
                "WDEF.L": "WisdomTree Europe Defence UCITS ETF",  

                # Multi-fundo / Balanced
                "VWRL.L": "Vanguard FTSE All-World UCITS ETF",
                "VUAG.L": "Vanguard S&P 500 UCITS ETF USD Acc",
                "CSP1.L": "iShares Core S&P 500 UCITS ETF USD Acc",
                "VWCE.DE": "Vanguard FTSE All-World UCITS ETF USD Acc (Equities)",
                "VWRP.L": "Vanguard FTSE All-World UCITS ETF USD Acc (Equities)",
                "EUNL.DE": "iShares Core MSCI World UCITS ETF USD Acc (Equities)",
                "VUAA.L": "Vanguard S&P 500 UCITS ETF USD Acc (Equities)",
                "CSPX.L": "iShares Core S&P 500 UCITS ETF USD Acc (Equities)",
                "IUSN.DE": "iShares MSCI World Small Cap UCITS ETF (Equities)",
                "WSML.L": "iShares MSCI World Small Cap UCITS ETF (Equities)",
                "EMIM.L": "iShares Core MSCI Emerging Markets IMI UCITS ETF (Equities)",
                "SPPW.DE": "SPDR MSCI World UCITS ETF (Equities)",
                "EXSA.DE": "iShares STOXX Europe 600 UCITS ETF (Equities)",
                "EXXT.DE": "iShares NASDAQ 100 UCITS ETF (Equities)",
                "QDVE.DE": "iShares S&P 500 Information Technology Sector UCITS ETF (Thematic)",
                "VFEA.AS": "Vanguard FTSE Developed Asia Pacific ex Japan UCITS ETF (Equities)",
                "VFEM.AS": "Vanguard FTSE Emerging Markets UCITS ETF (Equities)"
                }

symbol_br_indices = {
    "CDI":      "CDI (Taxa DI)",
    "IMA-B":    "IMA-B (NTN-B Total)",
    "IMA-B 5":  "IMA-B 5 (NTN-B até 5 anos)",
    "IMA-B 5+": "IMA-B 5+ (NTN-B acima de 5 anos)",
    "IDA-IPCA": "IDA-IPCA (Debentures IPCA+)",
    "IDKA PRE": "IDKA PRÉ 5A (Prefixado 5 anos)",
    "IHFA":     "IHFA (Hedge Funds)",
    "IFIX":     "IFIX (Fundos Imobiliários)",

    # Demais índices ANBIMA (histórico via Anbima/ + atualizar_indices_anbima.py)
    "IDA-DI":            "IDA-DI (Debêntures DI)",
    "IDA-GERAL":         "IDA-GERAL (Debêntures Geral)",
    "IDA-IPCA INFRA":    "IDA-IPCA Infraestrutura",
    "IDA-IPCA INFRA GROSSUP": "IDA-IPCA Infra Gross-up (Equivalente Tributado)",
    "IDA-IPCA EX-INFRA": "IDA-IPCA ex-Infraestrutura",
    "IDA-LIQ DI":        "IDA-LIQ DI (Debêntures líquidas DI)",
    "IDA-LIQ GERAL":     "IDA-LIQ Geral (Debêntures líquidas)",
    "IDA-LIQ IPCA":      "IDA-LIQ IPCA (Debêntures líquidas IPCA+)",
    "IDA-LIQ IPCA INFRA": "IDA-LIQ IPCA Infraestrutura",
    "IDKA PRE 3M":       "IDKA PRÉ 3M (Prefixado 3 meses)",
    "IDKA PRE 1A":       "IDKA PRÉ 1A (Prefixado 1 ano)",
    "IDKA PRE 2A":       "IDKA PRÉ 2A (Prefixado 2 anos)",
    "IDKA PRE 3A":       "IDKA PRÉ 3A (Prefixado 3 anos)",
    "IDKA IPCA 2A":      "IDKA IPCA 2A (Indexado IPCA 2 anos)",
    "IDKA IPCA 3A":      "IDKA IPCA 3A (Indexado IPCA 3 anos)",
    "IDKA IPCA 5A":      "IDKA IPCA 5A (Indexado IPCA 5 anos)",
    "IDKA IPCA 10A":     "IDKA IPCA 10A (Indexado IPCA 10 anos)",
    "IDKA IPCA 15A":     "IDKA IPCA 15A (Indexado IPCA 15 anos)",
    "IDKA IPCA 20A":     "IDKA IPCA 20A (Indexado IPCA 20 anos)",
    "IDKA IPCA 30A":     "IDKA IPCA 30A (Indexado IPCA 30 anos)",
    "IMA-B 5 P2":        "IMA-B 5 P2",
    "IMA-GERAL":         "IMA-GERAL (Renda Fixa Total)",
    "IMA-GERAL EX-C":    "IMA-GERAL ex-C (exclui NTN-C)",
    "IMA-S":             "IMA-S (LFT/Selic)",
    "IRF-M":             "IRF-M (Prefixado Total)",
    "IRF-M 1":           "IRF-M 1 (Prefixado até 1 ano)",
    "IRF-M 1+":          "IRF-M 1+ (Prefixado acima de 1 ano)",
    "IRF-M P2":          "IRF-M P2",
    "IRF-M P3":          "IRF-M P3",
}

benchmarks = {
    # Américas
    "^BVSP": "Ibovespa (Brazil)",
    "^GSPC": "S&P 500 Index (USA)",
    "^DJI": "Dow Jones Industrial Average (USA)",
    "^IXIC": "NASDAQ Composite (USA)",
    "^NDX": "NASDAQ 100 (USA)",
    "^RUT": "Russell 2000 (USA)",
    "^MXX": "IPC Mexico (Mexico)",
    "^IPSA": "Santiago IPSA (Chile)",
    "^COLCAP": "COLCAP (Colombia)",
    "^IGBVL": "S&P/BVL General Index (Peru)",
    "^MERVAL": "MERVAL (Argentina)",
    "^BVC": "Venezuela General Index",

    # Europa
    "^STOXX50E": "EURO STOXX 50",
    "^STOXX": "STOXX Europe 600",
    "^GDAXI": "DAX (Germany)",
    "^FCHI": "CAC 40 (France)",
    "FTSEMIB.MI": "FTSE MIB (Italy)",
    "^IBEX": "IBEX 35 (Spain)",
    "^FTSE": "FTSE 100 (UK)",
    "^OMX": "OMX Nordic 40 (Nordic)",
    "^SSMI": "SMI (Switzerland)",

    # Ásia e Oceania
    "^N225": "Nikkei 225 (Japan)",
    "^TOPX": "TOPIX (Japan)",
    "^HSI": "Hang Seng (Hong Kong)",
    "^STI": "Straits Times Index (Singapore)",
    "^AXJO": "ASX 200 (Australia)",
    "^NZ50": "NZX 50 (New Zealand)",
    "^BSESN": "BSE Sensex (India)",
    "^NSEI": "Nifty 50 (India)",
    "^KS11": "KOSPI (South Korea)",
    "^TWII": "TSEC Weighted Index (Taiwan)",
    "^JKSE": "Jakarta Composite (Indonesia)",
    "^KLSE": "FTSE Bursa Malaysia KLCI",
    "^SHCOMP": "Shanghai Composite (China)",
    "^SSEC": "Shanghai SE Composite Index",
    "^SZSE": "Shenzhen SE Composite Index",
    "^TA125.TA": "TA-125 (Israel)",

    # África e Oriente Médio
    "^JN0U.JO": "FTSE/JSE Top 40 (South Africa)",
    "^CASE30": "EGX 30 (Egypt)",
    "^TASI.SR": "Tadawul All Share Index (Saudi Arabia)",
    "^DFMGI": "DFM General Index (Dubai)",
    "^ADXI": "Abu Dhabi General Index (UAE)",

    # Global
    "^VIX": "CBOE Volatility Index (VIX)",

    "^SP500-10": "S&P 500 Energy Sector",
    "^SP500-15": "S&P 500 Materials Sector",
    "^SP500-20": "S&P 500 Industrials Sector",
    "^SP500-25": "S&P 500 Consumer Discretionary Sector",
    "^SP500-30": "S&P 500 Consumer Staples Sector",
    "^SP500-35": "S&P 500 Health Care Sector",
    "^SP500-40": "S&P 500 Financials Sector",
    "^SP500-45": "S&P 500 Information Technology Sector",
    "^SP500-50": "S&P 500 Communication Services Sector",
    "^SP500-55": "S&P 500 Utilities Sector",
    "^SP500-60": "S&P 500 Real Estate Sector",
    "^SXAP": "STOXX Europe 600 Automobiles & Parts",
    "^SX7P": "STOXX Europe 600 Banks",
    "^SXPP": "STOXX Europe 600 Basic Resources",
    "^SX4P": "STOXX Europe 600 Chemicals",
    "^SXOP": "STOXX Europe 600 Construction & Materials",
    "^SXFP": "STOXX Europe 600 Financial Services",
    "^SX3P": "STOXX Europe 600 Food & Beverage",
    "^SXDP": "STOXX Europe 600 Health Care",
    "^SXNP": "STOXX Europe 600 Industrial Goods & Services",
    "^SXIP": "STOXX Europe 600 Insurance",
    "^SXMP": "STOXX Europe 600 Media",
    "^SXEP": "STOXX Europe 600 Oil & Gas",
    "^SXQP": "STOXX Europe 600 Personal & Household Goods",
    "^SX86P": "STOXX Europe 600 Real Estate",
    "^SXRP": "STOXX Europe 600 Retail",
    "^SX8P": "STOXX Europe 600 Technology",
    "^SXKP": "STOXX Europe 600 Telecommunications",
    "^SXTP": "STOXX Europe 600 Travel & Leisure",
    "^SX6P": "STOXX Europe 600 Utilities",
    "^SXP1E": "STOXX Asia/Pacific 600 Index (Asia Pacific)",
    "^05NN.Z": "STOXX Asia/Pacific Div Select 50 Index",       
    "^403F.Z": "STOXX Asia/Pacific 600 Ax Value Index",        
    "^40HC.Z": "STOXX Asia/Pacific 600 Ax Low Risk Index",
    "^NQASIA10": "Nasdaq Asia Technology Index",
    "^ICEAT30": "NYSE Asia Tech 30 Index",
    "^NQEMASIA10": "Nasdaq EM Asia Technology Index",
    "^SPSEA4UN": "S&P Southeast Asia 40 Index",
    "^IBXX50": "IBrX 50 (50 ações mais negociadas)",
    "^IBXX100": "IBrX 100 (100 ações mais negociadas)",
    "^IGC": "Índice de Governança Corporativa (IGC)",
    "^IFNC": "Índice Financeiro (IFNC)",
    "^INDX": "Índice de Industriais (INDX)",
    "^IMOB": "Índice Imobiliário (IMOB)",
    "^ICON": "Índice de Consumo (ICON)",
    "^UTIL": "Índice de Utilidade Pública (UTIL)",
    "^IMAT": "Índice de Materiais Básicos (IMAT)",
    "^IDIV": "Índice de Dividendos (IDIV)",
    "^IEE": "Índice de Energia Elétrica (IEE)",
    "^MLCX": "Índice MidLarge Cap (MLCX)",
    "^SMLL": "Índice Small Cap (SMLL)",
    "^IBRA": "Índice Brasil Amplo (IBrA)",

    # Índices de renda fixa e fundos brasileiros (dados proprietários / BCB)
    "CDI":      "CDI (Taxa DI)",
    "IMA-B":    "IMA-B (NTN-B Total)",
    "IHFA":     "IHFA (Hedge Funds)",
}

symbol_info = symbol_real | symbol_dolar | symbol_euro | symbol_br_indices | benchmarks

# Tickers dos índices BR que NÃO vêm do yfinance (BCB ou planilhas)
BR_BENCH_TICKERS = {"CDI", "IMA-B", "IHFA"}

_br_full_df = None  # cache único da janela completa (2000 → hoje)


def _sgs_chunked(codes, start, end, years_per_chunk=9):
    import requests
    fmt_api = "%d/%m/%Y"
    start, end = pd.to_datetime(start), pd.to_datetime(end)
    result = {}
    for col_name, serie_id in codes.items():
        rows, cur = [], start
        while cur <= end:
            nxt = min(cur + pd.DateOffset(years=years_per_chunk) - pd.Timedelta(days=1), end)
            resp = requests.get(
                f"https://api.bcb.gov.br/dados/serie/bcdata.sgs.{serie_id}/dados",
                params={"formato": "json",
                        "dataInicial": cur.strftime(fmt_api),
                        "dataFinal": nxt.strftime(fmt_api)},
                timeout=30,
            )
            resp.raise_for_status()
            rows.extend(resp.json())
            cur = nxt + pd.Timedelta(days=1)
        dates = pd.to_datetime([d["data"] for d in rows], dayfirst=True)
        values = [float(d["valor"]) for d in rows]
        s = pd.Series(values, index=dates, name=col_name).sort_index()
        result[col_name] = s[~s.index.duplicated(keep="last")]
    return pd.DataFrame(result)


def _load_all_br_indices():
    """
    Carrega todos os índices BR do histórico completo (2000 → hoje).
    Cada série é construída de forma independente; o DataFrame final é
    montado com pd.concat para evitar problemas de alinhamento de índice.
    Erros são impressos no terminal para facilitar diagnóstico.
    """
    import sys

    def _anbima_excel(fname, field="Retorno"):
        path = _os.path.join(_BASE_DIR, fname)
        df = pd.read_excel(path)
        df["Data"] = pd.to_datetime(df["Data"], dayfirst=True, errors="coerce")
        df = df.rename(columns={"Data": "Date"}).set_index("Date")
        df.index = pd.to_datetime(df.index)
        df = df[~df.index.duplicated(keep="last")]
        return (df[field] / 100.0).dropna()

    _start = "2000-01-01"
    _end = pd.to_datetime("today").strftime("%Y-%m-%d")
    series = {}

    try:
        cdi = _sgs_chunked({"CDI": 12}, _start, _end)
        cdi.index = pd.to_datetime(cdi.index)
        cdi = cdi[~cdi.index.duplicated(keep="last")]
        series["CDI"] = (cdi["CDI"] / 100.0).dropna()
    except Exception as e:
        print(f"[Assets] CDI load error: {e}", file=sys.stderr)

    for col, fname in [
        ("IMA-B",    "IMA-B.xlsx"),
        ("IMA-B 5",  "IMA-B 5.xlsx"),
        ("IMA-B 5+", "IMA-B 5+.xlsx"),
        ("IDA-IPCA", "IDA-IPCA.xlsx"),
        ("IDKA PRE", "IDKA 5A.xlsx"),
        ("IHFA",     "IHFA.xlsx"),

        ("IDA-DI",             "IDA-DI.xlsx"),
        ("IDA-GERAL",          "IDA-Geral.xlsx"),
        ("IDA-IPCA INFRA",     "IDA-IPCA Infraestrutura.xlsx"),
        ("IDA-IPCA EX-INFRA",  "IDA-IPCA ex-Infraestrutura.xlsx"),
        ("IDA-LIQ DI",         "IDA-LIQ DI.xlsx"),
        ("IDA-LIQ GERAL",      "IDA-LIQ Geral.xlsx"),
        ("IDA-LIQ IPCA",       "IDA-LIQ IPCA.xlsx"),
        ("IDA-LIQ IPCA INFRA", "IDA-LIQ IPCA Infraestrutura.xlsx"),
        ("IDKA PRE 3M",        "IDKA 3M.xlsx"),
        ("IDKA PRE 1A",        "IDKA 1A.xlsx"),
        ("IDKA PRE 2A",        "IDKA 2A.xlsx"),
        ("IDKA PRE 3A",        "IDKA 3A.xlsx"),
        ("IDKA IPCA 2A",       "IDKA IPCA 2A.xlsx"),
        ("IDKA IPCA 3A",       "IDKA IPCA 3A.xlsx"),
        ("IDKA IPCA 5A",       "IDKA IPCA 5A.xlsx"),
        ("IDKA IPCA 10A",      "IDKA IPCA 10A.xlsx"),
        ("IDKA IPCA 15A",      "IDKA IPCA 15A.xlsx"),
        ("IDKA IPCA 20A",      "IDKA IPCA 20A.xlsx"),
        ("IDKA IPCA 30A",      "IDKA IPCA 30A.xlsx"),
        ("IMA-B 5 P2",         "IMA-B 5 P2.xlsx"),
        ("IMA-GERAL",          "IMA-Geral.xlsx"),
        ("IMA-GERAL EX-C",     "IMA-Geral ex-C.xlsx"),
        ("IMA-S",              "IMA-S.xlsx"),
        ("IRF-M",              "IRF-M.xlsx"),
        ("IRF-M 1",            "IRF-M 1.xlsx"),
        ("IRF-M 1+",           "IRF-M 1+.xlsx"),
        ("IRF-M P2",           "IRF-M P2.xlsx"),
        ("IRF-M P3",           "IRF-M P3.xlsx"),
    ]:
        try:
            series[col] = _anbima_excel(fname)
        except Exception as e:
            print(f"[Assets] {col} load error: {e}", file=sys.stderr)

    # Série derivada: a ANBIMA divulga o IDA-IPCA Infraestrutura como retorno
    # de mercado puro (sem ajuste de imposto — confirmado na metodologia
    # oficial do índice). Como a debênture incentivada é isenta de IR,
    # dividir o retorno diário por 0,85 (1 - 15%, alíquota mínima da tabela
    # regressiva) dá o equivalente bruto tributado, comparável a papéis sem
    # isenção.
    if "IDA-IPCA INFRA" in series:
        series["IDA-IPCA INFRA GROSSUP"] = series["IDA-IPCA INFRA"] / 0.85

    try:
        path = _os.path.join(_BASE_DIR, "IFIX.xlsx")
        ifix = pd.read_excel(path)
        ifix["Data"] = pd.to_datetime(ifix["Data"], dayfirst=True, errors="coerce")
        ifix = ifix.rename(columns={"Data": "Date"}).set_index("Date")
        ifix.index = pd.to_datetime(ifix.index)
        ifix = ifix[~ifix.index.duplicated(keep="last")]
        series["IFIX"] = ifix["Close"].pct_change().dropna()
    except Exception as e:
        print(f"[Assets] IFIX load error: {e}", file=sys.stderr)

    return pd.concat(series, axis=1) if series else pd.DataFrame()


def load_br_indices(start=None, end=None):
    """
    Retorna DataFrame de retornos diários dos índices BR proprietários/BCB.
    Colunas disponíveis: ver chaves de `symbol_br_indices`.
    Carrega o histórico completo uma vez e filtra por data nas chamadas seguintes.
    """
    global _br_full_df
    if _br_full_df is None:
        _br_full_df = _load_all_br_indices()

    if _br_full_df.empty or (start is None and end is None):
        return _br_full_df.copy()

    result = _br_full_df.copy()
    if start is not None:
        result = result[result.index >= pd.to_datetime(start)]
    if end is not None:
        result = result[result.index <= pd.to_datetime(end)]
    return result